version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    restart: always
